import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
   async function fetchData() {
    const response = await fetch('https://jsonplaceholder.typicode.com/todos/')
    const data = await response.json()
    console.log("data", data)
  }

  fetchData()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>My App Test</h1>
      </main>
    </>
  )
}
